services:
  postgres:
    container_name: postgres-sql-security
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - spring-security-network
  spring-boot-app:
    container_name: security-app
    image: security/demo:v1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8088:8080"
    networks:
      - spring-security-network
    depends_on:
      - postgres
volumes:
  postgres-data:

networks:
  spring-security-network:
    driver: bridge
